# Generated by Django 5.2.6 on 2025-09-17 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filesapp', '0002_financialfile_delete_uploadedfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialfile',
            name='csv_file',
            field=models.FileField(blank=True, null=True, upload_to='csv/'),
        ),
    ]
