# Generated by Django 5.2.6 on 2025-09-17 18:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filesapp', '0003_financialfile_csv_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('line', models.CharField(max_length=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('value', models.FloatField(default=0.0)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='filesapp.financialfile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
