# Generated by Django 5.2.6 on 2025-09-17 19:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filesapp', '0004_financialrow'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('file_type', models.CharField(choices=[('rozvaha', 'Rozvaha'), ('vysledovka', 'Výkaz zisku a ztráty')], max_length=20)),
                ('key', models.CharField(max_length=100)),
                ('value', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filesapp_analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Financial Analysis',
                'verbose_name_plural': 'Financial Analyses',
                'unique_together': {('user', 'year', 'file_type', 'key')},
            },
        ),
    ]
