# Generated by Django 5.2.6 on 2025-09-17 19:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filesapp', '0005_financialanalysis'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialanalysis',
            name='key',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='financialanalysis',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_analyses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='financialanalysis',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
